version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - phpForBeginnersNotesProject:/var/lib/mysql
    ports:
      - 3001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=notes

volumes:
  phpForBeginnersNotesProject:
